[Domain][User] -added new domain class user
arohablue/BlockDockServer pull request #3
Opened 2018-10-26 05:53 UTC by rhnmahajan83

-user table generated
-login backend support added
-created empty userApi controller for future use

2018-10-27 13:21 UTC, arohablue commented on grails-app/domain/blockdockserver/User.groovy
> +        emailId         email: true
Duplicate emaild constraints.

2018-10-27 15:46 UTC, arohablue requested changes
Left a comment in domain class

2018-10-27 19:21 UTC, rhnmahajan83 commented on grails-app/domain/blockdockserver/User.groovy
> +        emailId         email: true
for now let that be as it is lets make the change next time when we changer User.groovy domain class

2018-11-25 16:55 UTC, arohablue approved these changes

2018-11-25 16:55 UTC, merged